# Generated by Django 5.1.4 on 2024-12-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('academic_year', models.IntegerField()),
                ('faculty_id', models.IntegerField(blank=True, null=True)),
                ('course_number', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tb_course',
            },
        ),
        migrations.CreateModel(
            name='tb_faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=255)),
                ('faculty_password', models.CharField(max_length=50)),
                ('role_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_faculty',
            },
        ),
        migrations.CreateModel(
            name='tb_lesson_plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_id', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=255)),
                ('course_no', models.CharField(max_length=5)),
                ('course_id', models.IntegerField()),
                ('academic_year', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_lesson_plan',
            },
        ),
        migrations.CreateModel(
            name='tb_roles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(blank=True, max_length=45, null=True)),
                ('faculty', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tb_roles',
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='faculty',
        ),
        migrations.DeleteModel(
            name='LessonPlan',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
